observeinc/.github

.github/workflows/prerelease.yaml
Ports the changes from https://github.com/observeinc/terraform-observe-example/pull/12 upstream so that they can be more easily reused in other Terraform module repos.
Validated with https://github.com/observeinc/terraform-observe-example/actions/runs/2320479447 (which successfully produced a Slack notification and prerelease artifacts) and https://github.com/observeinc/terraform-observe-example/runs/6425912883 (which did not provide a Slack URL and successfully skipped the Slack notification steps while otherwise completing successfully).
=> ci: Add Slack notifications to prerelease workflow

.github/workflows/terraform-observe_prerelease.yaml, .github/workflows/terraform-observe_release.yaml
Similar to https://github.com/observeinc/.github/pull/8, this adds Slack notifications for when new releases take place. This differs in that it is performed for official releases, as opposed to prerelease artifacts.
Tested with https://github.com/observeinc/terraform-observe-example/runs/6429782863
=> ci: Add Slack notifications to release workflow

.github/workflows/terraform-observe_pre-commit-autoupdate.yaml, .github/workflows/terraform-observe_pre-commit.yaml
CI jobs that run `terraform validate` are failing because the Terraform CLI doesn't like downloading modules from S3 when no AWS credentials are present. As a quick workaround, we can add AWS credentials for our CI runs.
=> ci: Add AWS credentials for Terraform validation

.github/actions/terraform-observe/terraform-test-apply/action.yaml, .github/scripts/terraform_tests.sh, .github/workflows/terraform-observe_scheduler.yaml
(Note, this PR follows feedback from [a previously closed PR](https://github.com/observeinc/.github/pull/12); feel free to take a look at that for more context.)
Adds a ci job to the `terraform-observe-*` ci tests that does OPAL validation and fails in the case that a new commit has an observe resource with bad OPAL (or otherwise fails to be applied). 
What it does in detail:
1. installs terraform
2. checks out the repo
3. iterating through every `.tests/` subdirectory, creates a boilerplate `provider.tf`, and runs `terraform init`. If it does not find any `.tests/` subdirectories, it will fail with a message pointing to a readme for how to write tests. 
4. iterating through every `.tests/` subdirectory, runs `terraform apply` and `terraform plan`.  (applies with `-var …
=> feat: add ability to configure multiple opal validation tests

.github/workflows/terraform-observe_sync-from-template-repo.yaml
updates the `terraform-observe_sync-from-template-repo.yaml` workflow to...
1. be a bit simpler
2. also include any files in `scripts/*` in the content that gets synced from the template repo to children repos 
this is needed for the new terraform tests features we're adding
This workflow is pretty messy (started as more of a POC). We should probably clean it up someday. 
I've tested the changed `find` command locally and it works nicely. Gives me...
- all files under `.github/` excepting `.github/workflows/` (which workflows cannot update or you get an error)
- all files under `scripts/`
- all files matching the name `Makefile`, `.pre-commit-config.yaml`, or `LICENSE`
=> feat: add scripts to sync-from-template-repo

.github/workflows/terraform-observe_sync-from-template-repo.yaml
fixes the sync-from-template-repo workflow to search on the correct directory for "path" based searches (like `.github/*` and `.scripts/*` )
fix the sync workflow
Tested with a test repo and you can now see the "path" based files are picked up by the sync ([reference](https://github.com/observeinc/terraform-observe-estib-test2/actions/runs/2431141734)), and [the PR it generated](https://github.com/observeinc/terraform-observe-estib-test2/pull/8/files) includes the script files
=> fix: add directory files back to sync

.github/workflows/terraform-observe_scheduler.yaml
updates the find command for the get-test-directories job to look for tests in `tftest` rather than `.tests`
Would like to have it use the `make` command instead, but that was giving space-delimited directories in its results, not newline-delimited. Which wouldn't work well for if someone has directories that have spaces in them. 
Worked as expected in a test branch [here](https://github.com/observeinc/terraform-observe-estib-test1/actions/runs/2436035810)
=> ci: update get-test-directories to use tftests

.github/workflows/terraform-observe_prerelease.yaml
There are two issues with the versions on our prerelease artifacts right now:
1. If there are no tags in the repo, we get an invalid version that just consists of the short git hash for the repo. This is an invalid semantic version and it causes issues with Terraform tooling like the CLI and Hashicorp's `go-version` library
2. The base version for our prerelease artifacts is the same as the version for the latest release. In other words, if we've just released `1.5.1`, then the next change after that will result in a prerelease artifact with a version starting with `1.5.1` and then followed by the usual `-g<git hash>`. Instead, the base version should be the _next_ version we'll release, not the last version we released; for the example, that'd be either `1.5.2`, `1.6.0`, or `2.0.0`, …
=> fix: Correct prerelease artifact versions

.github/workflows/terraform-observe_release.yaml
Sets the `terraform-observe_release.yaml` workflow to skip cutting a release (and all subsequent related steps) when the changelog is empty. 
Allows us to automate releases on a schedule. 
- Tested empty release scenario on a side repo [here](https://github.com/observeinc/terraform-observe-slobsv-test1/runs/6870470849?check_suite_focus=true)
- Tested non-empty release scenario on a side repo [here](https://github.com/observeinc/terraform-observe-slobsv-test1/runs/6870755260?check_suite_focus=true)
All looks good to me.
=> ci: skip release cut if no changes

.github/workflows/terraform-observe_prerelease.yaml
1. Semantic versioning requires that prerelease versions adhere to the format `major.minor.patch-prerelease+metadata`, where `+metadata` is optional and `prerelease` consists of one or more segments separated by dot (`.`). This change tweaks our prerelease versions to adhere to that format correctly. The git commit hash is moved to the metadata portion of the version as it cannot be compared to other git hashes in isolation (i.e., without referencing information not present in the version itself).
2. It might be useful to build prerelease artifacts off of non-main (or non-master) branches. In order to facilitate that without making it difficult to distinguish between those artifacts and ones built off of main branches, an additional prerelease segment is added that consists of `alpha` for …
=> feat: Distinguish between official and unofficial prerelease versions, adhere correctly to semantic versioning for prereleases

.github/workflows/terraform-observe_prerelease.yaml
Forgot to update the `make s3` invocation to use the correct version when publishing S3 artifacts. Verified against the example module by manually invoking its prerelease action and ensuring that the corresponding S3 artifact had the correct version component in its path.
=> fix: Use correct prerelease version when publishing to S3

.github/workflows/pre-commit-autoupdate.yaml
the `.github/workflows/pre-commit-autoupdate.yaml` workflow has been failing for the `terraform-observe-example` repo (the one repo we care to be running it successfully) because the workflow does not have sufficient permissions to run the `peter-evans/create-pull-request` action. This PR adds the permissions that [its documentation](https://github.com/peter-evans/create-pull-request#action-inputs) says we need. 
enable pre-commit-autoupdate.yaml again
I did a test run of this branch's workflow and [it ran successfully](https://github.com/observeinc/terraform-observe-example/runs/7117730876?check_suite_focus=true)
=> ci: fix pre-commit auto-update permissions error

.github/actions/terraform-observe/terraform-test-apply/action.yaml
Pins terraform version to v1.2.9 since as soon as we started using 1.3.0 we started hitting errors like [this one](https://github.com/observeinc/terraform-observe-aws/actions/runs/3099567915/jobs/5018859948#step:2:6638).
Joao opened an issue on this [here](https://github.com/hashicorp/terraform/issues/31838), for reference.
=> feat: pin terraform v1-2-9 to avoid problems with 1-3-0

.github/workflows/tf-account.yaml
For the "Terraform Account" workflow, supports being called from workflows that run on `workflow_dispatch`. Also avoids hardcoding the default branch name, which allows the workflow to support repositories with `master` or other branch names.
=> terraform/account: run apply on any event on default branch

.github/actions/terraform-observe/terraform-test-apply/action.yaml, .github/workflows/terraform-observe_pre-commit.yaml, .github/workflows/tf-account.yaml, .github/workflows/tf-update-lock.yaml
v2.0.3 updates `@actions/core` to use environment files for outputs:
https://github.com/hashicorp/setup-terraform/releases/tag/v2.0.3
This fixes the following deprecation warning:
```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
The breaking change in v2 is that Node 16 is used instead of Node 12, which is really not breaking except in exceptional cases (self-hosted runners).
=> terraform: update `setup-terraform` action

.github/workflows/terraform-observe_pre-commit.yaml, .github/workflows/terraform-observe_scheduler.yaml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> use `$GITHUB_OUTPUT` env file to set outputs

.github/workflows/tf-account.yaml
Adds the Terraform plan to the [job summary](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary). While adding comments on a PR is readily discoverable, it comes with a handful of disadvantages:
* Creates lots of clutter when pushing multiple times
* Length limit is low (~65 KB)
Actions [added](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) job summaries earlier this year to help accommodate human-readable output while addressing the issues above.
For now, this is relatively invisible unless you know how to navigate to the job summary page. The new step only runs on pull requests, strictly because `terraform plan` only runs on pull requests. In a future PR, if I can both write the plan to a file …
=> terraform: add plan to job summary

.github/workflows/tf-account.yaml
* Adds a link to the job summary for the workflow run where the plan is included
* When the plan is too large for a comment, instead includes an italicized note that users can inspect the plan in the workflow summary, with a second link to the same place
https://observe.atlassian.net/browse/OB-12109
=> terraform: omit plans that exceed comment length limit

.github/workflows/pre-commit-autoupdate.yaml, .github/workflows/terraform-observe_pre-commit.yaml, .github/workflows/terraform-observe_prerelease.yaml, .github/workflows/terraform-observe_release.yaml, .github/workflows/tf-account.yaml
AWS is moving fairly slowly towards `v2` of this action. Node 12 is in its late stages of deprecation but they haven't made a major release that requires 16 yet. Instead, they're offering this alternate tag and dual-publishing.
https://github.com/aws-actions/configure-aws-credentials#notice-node12-deprecation-warning
There's still a `set-output` warning, reported here:
https://github.com/aws-actions/configure-aws-credentials/issues/601
Will submit a fix upstream for that.
=> deps: update `aws-actions/configure-aws-credentials` to use Node.js v16

.github/workflows/shared_commit-validation.yaml
Configures the Terraform commit validation jobs, which only apply to commits in pull requests, to only run when the event is `pull_request`. Called workflows inherit the event name of their caller.
Previously, calls to this workflow from any event other than `pull_request`, e.g., `workflow_dispatch`, would cause these jobs to fail, given that the actions called in their steps expect to run on a PR:
https://github.com/observeinc/terraform-observe-gitlab/actions/runs/4108000982
=> terraform: run PR validation jobs on PR events

.github/workflows/terraform-observe_scheduler.yaml, .github/workflows/tf-account.yaml, .github/workflows/tf-update-lock.yaml
Allows jobs and users to customize the version of terraform that we use in Github Actions. Jobs can customize the terraform version through the `var` context. Users can customize the terraform version when they manually kick off a Github Actions job
=> Accept `terraform-version` as optional workflow input

.github/workflows/terraform-observe_pre-commit.yaml, .github/workflows/terraform-observe_scheduler.yaml
(note: will be squashing commits when merging)
This new CI job will validate that the `iconUrl` attribute of the `manifest.yaml` file in our repositories (if the file exists) comes from the `assets.observeinc.com` domain. It will skip the check if the `manifest.yaml` file does not exist.
=> Icon validation

.github/workflows/terraform-observe_scheduler.yaml
Addresses feedback from the [previous PR](https://github.com/observeinc/.github/pull/56):
* job name has been fixed to be in the proper style
* removes `env` from `get_icon_url` step left over from previous implementation
* utilizes GitHub annotations for error message
=> fix: validate-app-icon cleanup

.github/workflows/terraform-observe_pre-commit.yaml
Defines `tflint-version` as an input to the callable workflow, with the default set to the currently hardcoded value. For existing callers, this is a noop. In general, we should avoid mixing parameters and logic. A caller might use this to:
* Pin an older version in case of module-specific incompatibilities
* Test a newer version
=> pre-commit: accept TFLint version as input

.github/workflows/terraform-observe_scheduler.yaml
This PR makes the `yq` check for the value of `iconUrl` case insensitive. Tested locally.
=> fix: iconUrl key is case insensitive

.github/workflows/terraform-observe_scheduler.yaml
This addition to the app icon check GitHub Actions job will follow the provided link and ensure that the link returns a valid response.
=> feat: validate that app icon URL works

.github/workflows/terraform-observe_scheduler.yaml
Assumed this existed in #63, but `yq` doesn't publish semver tags for use in actions.
**The workflow is broken until this is merged.**
Please be aware of this when adding functionality, as it creates a large maintenance burden when we need to approve every single patch release for an active tool. Actions that do not offer semver tags should generally be avoided, particularly things like `yq` where an action is co-located in the main application repo.
Given that the uses of `yq` and especially `linkcheck` are trivial I'll look to replace the former with a different installation method and remove the latter in favor of a simpler tool (`curl` is plenty here) soon.
=> restore exact yq version

.github/workflows/terraform_release.yaml
Adds an optional `push` input to the Terraform release workflow, enabled by default. By disabling this input, users can see how the new release would be generated without actually writing any results back to the repository. 
Tested via https://github.com/observeinc/terraform-aws-lambda/pull/55.
=> release: add optional `push` input

CONTRIBUTING.md
Adds contributor guidelines, which are linked in the UI when opening PRs. They inform contributors that they can make changes to existing workflows stored here, but shouldn't be introducing breaking changes or new workflows.
Going forward, we should build new workflows in dedicated repositories. Work to split up this repository to enable easier maintenance including the ability to make breaking changes is tracked here:
https://observe.atlassian.net/browse/OB-16102
=> Add contributor guidelines

.github/workflows/tf-account.yaml
Pass around the plan as a file. Fixes "Argument list too long" errors.
See discussion: https://github.com/actions/github-script/issues/266
Failing job: https://github.com/observeinc/tf-account-auditboard/actions/runs/4504586394/jobs/7929250161
Also uploads the plan as an artifact for easier access when it's so large that it doesn't fit in the job summary (several megabytes). This is still easier than trying to hunt it down via the log viewer, which tries to stream log lines and can be very slow for a plans that's many thousands of lines.
Follow up to #43/#45. Due to the verbosity and lack of schema of `observe_dashboard`, it can trigger extremely long plans, potentially several kilobytes.
=> tf-account: pass plan via file

.github/workflows/terraform-observe_scheduler.yaml
updates the default terraform version of our tftests
some of our stuff needs 1.3+ flavors, and i don't much like the idea of all the content repos having their own versions passed in for their tftests. 
haven't really, but if stuff breaks in tests we should find out quickly and that would just mean that there's a breaking change in terraform, so we'd be able to override with a specific version.
=> ci: update default terraform version to latest

.github/workflows/terraform-observe_sync-from-template-repo.yaml
adds the `.tflint.hcl` to the workflow that syncs all the children app repos from their template (terraform-observe-example)
Will unlock custom TFlinting capabilities for all the app repos without having to manually generate PRs on all of them all the time (as we update it)
Honestly haven't really. I think we can just try the workflow out on a child repo and carefully watch the results.
=> feat: update sync-from-template-repo workflow to also sync the .tflint.hcl file

.github/workflows/terraform-observe_pre-commit.yaml
Adds github token to the "setup tflint" step of pre-commit workflow. 
We need that workflow to use a github token to authenticate with `tflint --init` so that we don't get [rate limited](https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting). 
For context, [here's the source](https://github.com/terraform-linters/setup-tflint#using-custom-github-token) of what i referred to to understand how we need to pass in the token.
=> fix: add github_token to pre-commit setup tflint step

.github/workflows/tf-account.yaml
We've let the terraform version lag for a while, but the config-driven state management in version 1.5 is useful for tf-account.
=> feat: bump terraform version for tf-account

.github/workflows/tf-account.yaml
This commit adds:
- the ability to optionally configure an OAuth tailscale client to connect to an existing tailnet
- the ability to specify HTTPS_PROXY and NO_PROXY for use in `terraform plan` and `apply`
Combining both features a user can proxy requests to the Observe API through an access node in a tailscale network.
=> feat: allow specifying HTTPS_PROXY, NO_PROXY, TS_TAGS

.github/workflows/terraform-observe_release.yaml
Adds a check to make sure that the `Release and Push` workflow only runs from the default branch (usually `main`), stops people from accidentally running the `Release and Push` workflow from a non-default branch. 
I've tested on a throwaway repo with success:
- Ran the job from a non-main and it [successfully errored](https://github.com/observeinc/terraform-observe-slobsv-test2/actions/runs/5826786434) with a nice error log
- Ran the job from a main branch and it [successfully ran the job](https://github.com/observeinc/terraform-observe-slobsv-test2/actions/runs/5826769476)
Closes #86
=> feat: make sure release only happens on default_branch like main

.github/workflows/terraform-observe_pre-commit.yaml
This bumps the tflint version version to `v0.45.0`.  We need this version because our observe plugin for tflint requires API version 11 and the tflint version are using only support up to version 10.
Note that I chose this version because I've seen a few other repos using this as an override.
=> fix: bump tflint version to pass ci tests

.github/workflows/tf-account.yaml
When twingate-enabled is set to true, a twingate client is started using a pre-defined service key for a "github_actions" service account.
No proxies are required with Twingate (unlike Tailscale) because DNS records get overridden for select endpoints. The service account is currently setup to route traffic through Twingate for cap1 DNS names {155210249240,168414722295}.cap1.observeinc.com.
Next up:
* a PR for tf-account-cap-one to switch tailscale->twingate
* a PR here to remove tailscale support
=> feat: allow setting twingate-enabled

.github/workflows/terraform-observe_prerelease.yaml, .github/workflows/terraform-observe_release.yaml
Adds input to release workflows so repo name for slack notification can be overridden for repo renames
https://github.com/observeinc/terraform-observe-google-cloud-monitoring/actions/runs/8012769868
=> feat: repo input for repositories with changed names

.github/workflows/tf-account.yaml
It is more convenient to manage secrets in github than to interact with AWS secretsmanager. Unfortunately, doing so naively would make it impossible for an operator to run terraform manually if a complex state operation were to be necessary. As a workaround, we can ensure that secrets with prefix `X_` are synchronized to secretsmanager on every workflow run.
=> feat: synchronize github secrets to secretsmanager

.github/scripts/main.py, .github/workflows/terraform-observe_scheduler.yaml, .gitignore
Creates a python script that will associate each test directory with a customer id that is passed in as a comma separated list via GHA secret.  Assumes that all environments are in staging and all have same content reviewer username and password.
3 of 4 existing variables stay the same and only array of customer ids is new.
=> fix: OB-28708 add round robin

.github/workflows/terraform-observe_scheduler.yaml
See https://observe.atlassian.net/browse/OB-28707
Reduces load on staging api server by reducing parallel terraforming against it to 3
=> fix: reduce parallelism in terraform-observe_scheduler.yaml

.github/workflows/terraform-observe_scheduler.yaml
- Updates scheduled tests to include retries for failing tests
- Tested in `terraform-observe-host` which always had failing tests and seems to work well
See: 
- https://github.com/observeinc/terraform-observe-host/actions/runs/11582343232/job/32245166871#annotation:6:3766
- https://observe.atlassian.net/browse/OB-28707?focusedCommentId=210284
=> feat: add retry for terraform scheduled tests

.github/workflows/terraform-observe_scheduler.yaml
- Adds 60s backoff for retries
=> ci: update terraform-observe_scheduler.yaml to include backoff for retry
